### ISSUE TITLE
Enter/return key does not work

### ISSUE THREAD

**Issue by felipebutcher** [nick-shmyrev/improved-osk-gnome-ext#11] opened 2021-08-04 17:52 UTC
Hey there. Sorry to be opening this issue here. It happens even with the native onscreen keyboard on Gnome. But I am opening to know if anyone has a workaround to this.

When you open a text editor like gedit or any other text field, when you press enter the line doesn't break. In other words, the enter/return key doesn't work the same as the physical keyboard key.

Does anyone have a workaround for this?

**Comment by SamLukeYes** [comment] 2021-08-05 05:24
I can't reproduce this on Arch Linux with GNOME Shell 40.3. What's your distro and GNOME Shell version?

**Comment by nick-shmyrev** [comment] 2021-08-05 14:37
Sorry, I also can't reproduce this on Fedora 33 with Gnome 3.38. Perhaps you have another Gnome extension somehow interfering with Enter key?
If you run this command `journalctl /usr/bin/gnome-shell -f -o cat` and press Enter on onscreen keyboard, are you getting any errors?

**Comment by felipebutcher** [comment] 2021-08-06 17:18
Hey guys! Thank you for replying @SamLukeYes and @nick-shmyrev 

I am using Ubuntu 21.04, Gnome 3.38.5.

Nick, trying running your command. It doesn't show any output for the enter/return key and it shows outputs for every other keys.

**Comment by nick-shmyrev** [comment] 2021-08-07 15:14
> Nick, trying running your command. It doesn't show any output for the enter/return key and it shows outputs for every other keys.

What does it show for every other key?

I also tried Ubuntu 21.04 in a VM and still could not reproduce the issue. Have you been running your system for a while, or is it a fresh install? If it's the former, have you tried booting Ubuntu 21.04 from a live USB and checking if the keyboard works there?

Perhaps another extension is messing something up in your system? You can check this by disabling all user extensions, rebooting and checking if the default onscreen keyboard works as expected. You can disable extensions by running this command:
```bash
gsettings set org.gnome.shell disable-user-extensions true
```

If you're running a fresh install and disabling extensions didn't help, you might want to create an issue here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues

**Comment by nick-shmyrev** [comment] 2021-08-11 04:00
Not sure if it's related, but after searching for the warning messages you're getting, I found this thread: https://bbs.archlinux.org/viewtopic.php?id=245058.
Check it out, maybe it'll help?

**Comment by nick-shmyrev** [comment] 2021-08-13 20:44
Closing the issue since it doesn't seem to be caused by this extension.

**Closed by nick-shmyrev** 2021-08-13 20:44 UTC
