### ISSUE TITLE
Gnome 44 support

### ISSUE THREAD

**Issue by LeSnake04** [nick-shmyrev/improved-osk-gnome-ext#38] opened 2023-03-12 16:48 UTC
Gnome 44 will come out on the 22.03 this year and is already available in gnome OS. It would be great if this extension is available when it releases on popular distros

Fedora plans to release version 38 on the 25.04, so it would be great, if this is done by that date and the release of Ubuntu 23.04 and other distros.

Related: #30

**Comment by nick-shmyrev** [comment] 2023-03-13 17:34
I prefer to add support for new Gnome versions only after they've been fully released. Beta versions might have bugs that will be fixed in the full release, and I'd rather not spend time figuring the root cause of the issue, and then overriding another piece of original OSK code that I would then have to either maintain, or remove/rewrite. Release versions might also introduce bugs which might make the OSK partially/fully unusable.

Right now, "Ctrl + Shift + [key]" key combinations in Fedora 38.beta (with gnome-shell 44.rc) aren't working in OSK. This might be fixed by the time Gnome 44 is released, or later, when Fedora 38 gets a full release. If not, I'll take a look.

If you want to be able to use this extension the day Fedora 38 ships, or test if out yourself right now, you can either manually add "44" to a list of supported versions in `metadata.json` file and proceed with the manual installation, or disable extension version validation check and install from [extensions.gnome.org](https://extensions.gnome.org/extension/4413/improved-osk/):
```console
gsettings set org.gnome.shell disable-extension-version-validation true
```

**Comment by LeSnake04** [comment] 2023-03-21 18:32
I probably need to wait 1-2 weeks after the fedora release anyway until my other extensions update.

It will be more than enough if its available then. But I don't want to wait 3 months like I did the gnome 43 update.

I can test it on my arch PC to help

**Comment by nick-shmyrev** [comment] 2023-03-21 19:20
> It will be more than enough if its available then. But I don't want to wait 3 months like I did the gnome 43 update.

I don't want to sound rude or harsh, but developing this extension is my hobby, not a job. I work on it when I have free time and am in the mood to do so.

You're more than welcome to make a PR that would add Gnome 44 support right now, and I'd be happy to merge it in, provided everything works as expected. There's a list of some of the test cases I usually check [here](https://github.com/nick-shmyrev/improved-osk-gnome-ext/blob/master/TEST_CASES.md).

Or, you can make your own fork, that's what I did when the previous maintainer abandoned their fork, and what the previous maintainer did when the original author abandoned the original version.

**Comment by LeSnake04** [comment] 2023-03-22 00:01
@nick-shmyrev Sorry, I didn't mean to be rude. 

I love this extension and am so thankful for ur work. I especially love the ability to use control shortcuts in tablet mode?
 I sadly don't know anything about to do gnome extensions or js and already have too many side projects.

I can still test on gnome 44 to hopefully help you speed up the development process a bit. 
I don't like the frequency gnome devs are breaking extensions as well. 

Also, feel free to link to a donation page in the
README, so users with some spare money can gift you some drinks as a thanks.

**Closed** 2023-04-27 14:29 UTC
